on: [push]

jobs:
  gemini_md_job:
    runs-on: ubuntu-latest
    name: Convert Gemtext job
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - name: Gemini2md step
        id: gem2md
        uses: shrmpy/actions-gemini2md@v1

